### ISSUE TITLE
[ComputerVision] maxRetry error in sample code

### ISSUE THREAD

**Issue by luiscantero** [Azure-Samples/cognitive-services-dotnet-sdk-samples#184]
## API Name (Kind)
`ComputerVision`

## Issue Description
The following sample contains wrong code to retry fetching the results of the async operation:
https://github.com/Azure-Samples/cognitive-services-dotnet-sdk-samples/blob/master/documentation-samples/quickstarts/ComputerVision/Program.cs

Original code:
`
int i = 0;
int maxRetries = 10;
ReadOperationResult results;
do
{
    results = await client.GetReadOperationResultAsync(operationId);
    Console.WriteLine("Server status: {0}, waiting {1} seconds...", results.Status, i);
    await Task.Delay(1000);
    if (maxRetries == 9)
    {
        Console.WriteLine("Server timed out.");
    }
}
while ((results.Status == TextOperationStatusCodes.Running ||
    results.Status == TextOperationStatusCodes.NotStarted) && i++ < maxRetries);
`

Errors:
1. maxRetries should be a const (in order to catch the following errors).
2. The Console.WriteLine message shows "waiting {1} seconds", which is equivalent to showing $"waiting {i} seconds". However, the variable i gets increased in every iteration, but the code always waits 1 second, it doesn't vary.
3. The line "if (maxRetries == 9)" should use i instead of maxRetries, because i gets increased, not maxRetries.

Corrected code:
`
int i = 0;
const int MAX_RETRIES = 10;
ReadOperationResult results;
do
{
    results = await visionService.GetReadOperationResultAsync(operationId);

    if (results.Status != TextOperationStatusCodes.Succeeded)
    {
        Console.WriteLine($"Server status: {results.Status}, waiting 1 s ...");
        await Task.Delay(1000);
        if (i == 9)
        {
            Console.WriteLine("Server timed out");
        }
    }
}
while ((results.Status == TextOperationStatusCodes.Running ||
    results.Status == TextOperationStatusCodes.NotStarted) && i++ < MAX_RETRIES);
`

**Comment by yangyuan** [comment]
Thanks for reporting this issue. A fix will come soon.

**Comment by wiazur** [comment]
Thanks @luiscantero, the maxRetries is a typo, thanks for pointing that out. However the waiting code is correct, it is just accumulative rather than an iterating timer.

For instance if the status is on `Running` for more than a second, it will keep printing out each second. It would then look like this:
Server status: Running, waiting 0 seconds...
Server status: Running, waiting 1 seconds...
Server status: Running, waiting 2 seconds...

So you know the number of seconds increases compared to the last one. The actual wait time printed does not increase, it's always one second of wait time. I hope that clarifies things. If you have any other problems, let us know. Thank you.
